interface ClassData {
  id: number;
  price: number;
  duration: string;
  session: number;
  transmision: string;
  vehicleType: string;
}

const column: string[] = [
  "Id",
  "Price",
  "Duration",
  "Session",
  "Transmision",
  "Vehicle Type",
  "Action",
];

const data: ClassData[] = [
  {
    id: 1,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "SUV",
  },
  {
    id: 2,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 3,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 4,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 5,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 6,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 7,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 8,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 9,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 10,
    price: 100,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Sedan",
  },
  {
    id: 11,
    price: 120,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "SUV",
  },
  {
    id: 12,
    price: 130,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Hatchback",
  },
  {
    id: 13,
    price: 140,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "Coupe",
  },
  {
    id: 14,
    price: 150,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Convertible",
  },
  {
    id: 15,
    price: 160,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "Sedan",
  },
  {
    id: 16,
    price: 170,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "SUV",
  },
  {
    id: 17,
    price: 180,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "Truck",
  },
  {
    id: 18,
    price: 190,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Van",
  },
  {
    id: 19,
    price: 200,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "Hatchback",
  },
  {
    id: 20,
    price: 210,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Coupe",
  },
  {
    id: 21,
    price: 220,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "SUV",
  },
  {
    id: 22,
    price: 230,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Convertible",
  },
  {
    id: 23,
    price: 240,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "Truck",
  },
  {
    id: 24,
    price: 250,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Hatchback",
  },
  {
    id: 25,
    price: 260,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "Van",
  },
  {
    id: 26,
    price: 270,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Coupe",
  },
  {
    id: 27,
    price: 280,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "Sedan",
  },
  {
    id: 28,
    price: 290,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "SUV",
  },
  {
    id: 29,
    price: 300,
    duration: "2.5 hr",
    session: 3,
    transmision: "Manual",
    vehicleType: "Convertible",
  },
  {
    id: 30,
    price: 310,
    duration: "2.5 hr",
    session: 3,
    transmision: "Automatic",
    vehicleType: "Truck",
  },
];

export { column, data };
